ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;
ALTER SESSION SET NLS_LENGTH_SEMANTICS = CHAR;

-- ============================================================
-- DDL: テーブル作成
-- ============================================================

-- SRC_CUSTOMER（移行元 - 顧客）
CREATE TABLE SRC_CUSTOMER (
    CUSTOMER_ID      NUMBER PRIMARY KEY,
    CUSTOMER_NAME    VARCHAR2(100),
    ADDRESS          VARCHAR2(200),
    CUSTOMER_TYPE_ID VARCHAR2(3),
    DELETE_FLAG      NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY       VARCHAR2(50),
    CREATED_AT       DATE,
    UPDATED_BY       VARCHAR2(50),
    UPDATED_AT       DATE
);

-- SRC_CONTRACT（移行元 - 契約）
CREATE TABLE SRC_CONTRACT (
    CONTRACT_ID  NUMBER PRIMARY KEY,
    CUSTOMER_ID  NUMBER NOT NULL,
    ENERGY_TYPE  VARCHAR2(10),
    STATUS       VARCHAR2(20),
    START_DATE   DATE,
    END_DATE     DATE,
    REMARK1      VARCHAR2(200),
    REMARK2      VARCHAR2(200),
    REMARK3      VARCHAR2(200),
    REMARK4      VARCHAR2(200),
    REMARK5      VARCHAR2(200),
    REMARK6      VARCHAR2(200),
    REMARK7      VARCHAR2(200),
    REMARK8      VARCHAR2(200),
    REMARK9      VARCHAR2(200),
    REMARK10     VARCHAR2(200),
    REMARK11     VARCHAR2(200),
    REMARK12     VARCHAR2(200),
    REMARK13     VARCHAR2(200),
    REMARK14     VARCHAR2(200),
    REMARK15     VARCHAR2(200),
    REMARK16     VARCHAR2(200),
    REMARK17     VARCHAR2(200),
    REMARK18     VARCHAR2(200),
    REMARK19     VARCHAR2(200),
    REMARK20     VARCHAR2(200),
    DELETE_FLAG  NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY   VARCHAR2(50),
    CREATED_AT   DATE,
    UPDATED_BY   VARCHAR2(50),
    UPDATED_AT   DATE,
    CONSTRAINT FK_CONTRACT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES SRC_CUSTOMER (CUSTOMER_ID) DISABLE
);

-- SRC_BILLING（移行元 - 請求）
CREATE TABLE SRC_BILLING (
    BILLING_ID   NUMBER PRIMARY KEY,
    CONTRACT_ID  NUMBER NOT NULL,
    BILL_MONTH   VARCHAR2(6),
    TOTAL_AMOUNT NUMBER(10,2),
    DELETE_FLAG  NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY   VARCHAR2(50),
    CREATED_AT   DATE,
    UPDATED_BY   VARCHAR2(50),
    UPDATED_AT   DATE,
    CONSTRAINT FK_BILLING_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES SRC_CONTRACT (CONTRACT_ID) DISABLE
);

-- SRC_BILLING_DETAIL（移行元 - 請求明細）
CREATE TABLE SRC_BILLING_DETAIL (
    BILLING_DETAIL_ID NUMBER PRIMARY KEY,
    BILLING_ID        NUMBER NOT NULL,
    ITEM_TYPE         VARCHAR2(50),
    USAGE_QTY         NUMBER(10,2),
    UNIT_PRICE        NUMBER(10,2),
    AMOUNT            NUMBER(10,2),
    DELETE_FLAG       NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY        VARCHAR2(50),
    CREATED_AT        DATE,
    UPDATED_BY        VARCHAR2(50),
    UPDATED_AT        DATE,
    CONSTRAINT FK_BILLING_DETAIL_BILLING FOREIGN KEY (BILLING_ID) REFERENCES SRC_BILLING (BILLING_ID) DISABLE
);

-- MST_ENERGY_TYPE（エネルギータイプマスタ）
CREATE TABLE MST_ENERGY_TYPE (
    ENERGY_TYPE_ID       NUMBER PRIMARY KEY,
    ENERGY_NAME_JAPANESE VARCHAR2(20),
    ENERGY_NAME_SHORT    VARCHAR2(20),
    DELETE_FLAG          NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY           VARCHAR2(50),
    CREATED_AT           TIMESTAMP,
    UPDATED_BY           VARCHAR2(50),
    UPDATED_AT           TIMESTAMP
);

-- MST_INVOICE_STATUS（インボイスステータスマスタ）
CREATE TABLE MST_INVOICE_STATUS (
    STATUS_ID   NUMBER(3) PRIMARY KEY,
    STATUS_CODE VARCHAR2(3) NOT NULL UNIQUE,
    STATUS_NAME VARCHAR2(50),
    DESCRIPTION VARCHAR2(200),
    DELETE_FLAG NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY  VARCHAR2(50),
    CREATED_AT  TIMESTAMP,
    UPDATED_BY  VARCHAR2(50),
    UPDATED_AT  TIMESTAMP
);

-- MST_CUSTOMER_TYPE_CONVERSION（顧客種別変換マスタ）
CREATE TABLE MST_CUSTOMER_TYPE_CONVERSION (
    CONVERSION_ID NUMBER PRIMARY KEY,
    SOURCE_TYPE   VARCHAR2(3) NOT NULL, -- 旧顧客種別コード（001, 101など）
    TARGET_TYPE   NUMBER NOT NULL,
    DESCRIPTION   VARCHAR2(200),
    DELETE_FLAG   NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY    VARCHAR2(50),
    CREATED_AT    TIMESTAMP,
    UPDATED_BY    VARCHAR2(50),
    UPDATED_AT    TIMESTAMP,
    CONSTRAINT UK_MST_CUSTOMER_TYPE_CONV UNIQUE (SOURCE_TYPE)
);

-- TGT_CUSTOMER（移行先 - 顧客）
CREATE TABLE TGT_CUSTOMER (
    CUSTOMER_ID      NUMBER PRIMARY KEY,
    CUSTOMER_NAME    VARCHAR2(100),
    ADDRESS          VARCHAR2(200),
    CUSTOMER_TYPE_ID NUMBER,
    DELETE_FLAG      NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY       VARCHAR2(50),
    CREATED_AT       TIMESTAMP,
    UPDATED_BY       VARCHAR2(50),
    UPDATED_AT       TIMESTAMP
);

-- TGT_CONTRACT（移行先 - 契約）
CREATE TABLE TGT_CONTRACT (
    CONTRACT_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    STATUS_CODE VARCHAR2(20),
    START_DATE  DATE,
    END_DATE    DATE,
    DELETE_FLAG NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY  VARCHAR2(50),
    CREATED_AT  TIMESTAMP,
    UPDATED_BY  VARCHAR2(50),
    UPDATED_AT  TIMESTAMP,
    CONSTRAINT FK_TGT_CONTRACT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES TGT_CUSTOMER (CUSTOMER_ID) DISABLE
);

-- TGT_CONTRACT_ENERGY（多対多対応）
CREATE TABLE TGT_CONTRACT_ENERGY (
    CONTRACT_ENERGY_ID NUMBER PRIMARY KEY,
    CONTRACT_ID        NUMBER NOT NULL,
    ENERGY_TYPE_ID     NUMBER NOT NULL,
    DELETE_FLAG        NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY         VARCHAR2(50),
    CREATED_AT         TIMESTAMP,
    UPDATED_BY         VARCHAR2(50),
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT FK_CONTRACT_ENERGY_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES TGT_CONTRACT (CONTRACT_ID) DISABLE,
    CONSTRAINT FK_CONTRACT_ENERGY_ENERGY FOREIGN KEY (ENERGY_TYPE_ID) REFERENCES MST_ENERGY_TYPE (ENERGY_TYPE_ID) DISABLE,
    CONSTRAINT UK_CONTRACT_ENERGY UNIQUE (CONTRACT_ID, ENERGY_TYPE_ID)
);

-- TGT_CONTRACT_REMARK_A（REMARK 1〜10）
CREATE TABLE TGT_CONTRACT_REMARK_A (
    CONTRACT_ENERGY_ID NUMBER PRIMARY KEY,
    REMARK1            VARCHAR2(50),
    REMARK2            VARCHAR2(75),
    REMARK3            VARCHAR2(50),
    REMARK4            VARCHAR2(100),
    REMARK5            VARCHAR2(20),
    REMARK6            VARCHAR2(20),
    REMARK7            VARCHAR2(20),
    REMARK8            VARCHAR2(20),
    REMARK9            VARCHAR2(10),
    REMARK10           VARCHAR2(200),
    DELETE_FLAG        NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY         VARCHAR2(50),
    CREATED_AT         TIMESTAMP,
    UPDATED_BY         VARCHAR2(50),
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT FK_REMARK_A_CONTRACT_ENERGY FOREIGN KEY (CONTRACT_ENERGY_ID) REFERENCES TGT_CONTRACT_ENERGY (CONTRACT_ENERGY_ID) DISABLE
);

-- TGT_CONTRACT_REMARK_B（REMARK 11〜20）
CREATE TABLE TGT_CONTRACT_REMARK_B (
    CONTRACT_ENERGY_ID NUMBER PRIMARY KEY,
    REMARK11           VARCHAR2(20),
    REMARK12           VARCHAR2(200),
    REMARK13           VARCHAR2(10),
    REMARK14           VARCHAR2(50),
    REMARK15           VARCHAR2(30),
    REMARK16           VARCHAR2(50),
    REMARK17           VARCHAR2(20),
    REMARK18           VARCHAR2(50),
    REMARK19           VARCHAR2(200),
    REMARK20           VARCHAR2(100),
    DELETE_FLAG        NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY         VARCHAR2(50),
    CREATED_AT         TIMESTAMP,
    UPDATED_BY         VARCHAR2(50),
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT FK_REMARK_B_CONTRACT_ENERGY FOREIGN KEY (CONTRACT_ENERGY_ID) REFERENCES TGT_CONTRACT_ENERGY (CONTRACT_ENERGY_ID) DISABLE
);

-- TGT_INVOICE（移行先 - 請求ヘッダ）
CREATE TABLE TGT_INVOICE (
    INVOICE_ID   NUMBER PRIMARY KEY,
    CONTRACT_ID  NUMBER NOT NULL,
    INVOICE_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2),
    STATUS_ID    NUMBER,
    DELETE_FLAG  NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY   VARCHAR2(50),
    CREATED_AT   TIMESTAMP,
    UPDATED_BY   VARCHAR2(50),
    UPDATED_AT   TIMESTAMP,
    CONSTRAINT FK_INVOICE_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES TGT_CONTRACT (CONTRACT_ID) DISABLE,
    CONSTRAINT FK_INVOICE_STATUS FOREIGN KEY (STATUS_ID) REFERENCES MST_INVOICE_STATUS (STATUS_ID) DISABLE
);

-- TGT_INVOICE_DETAIL（移行先 - 請求明細）
CREATE TABLE TGT_INVOICE_DETAIL (
    INVOICE_DETAIL_ID NUMBER PRIMARY KEY,
    INVOICE_ID        NUMBER NOT NULL,
    ENERGY_TYPE_ID    NUMBER NOT NULL,
    USAGE_QTY         NUMBER(10,2),
    UNIT_PRICE        NUMBER(10,2),
    AMOUNT            NUMBER(10,2),
    DELETE_FLAG       NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_BY        VARCHAR2(50),
    CREATED_AT        TIMESTAMP,
    UPDATED_BY        VARCHAR2(50),
    UPDATED_AT        TIMESTAMP,
    CONSTRAINT FK_INVOICE_DETAIL_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES TGT_INVOICE (INVOICE_ID) DISABLE,
    CONSTRAINT FK_TGT_INVOICE_DETAIL_ENERGY FOREIGN KEY (ENERGY_TYPE_ID) REFERENCES MST_ENERGY_TYPE (ENERGY_TYPE_ID) DISABLE
);

EXIT;
