ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;
ALTER SESSION SET NLS_LENGTH_SEMANTICS = CHAR;

-- 契約×エネルギー関連テーブル（サロゲートキー）
CREATE SEQUENCE SEQ_CONTRACT_ENERGY_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

EXIT;
