ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;
ALTER SESSION SET NLS_LENGTH_SEMANTICS = CHAR;

-- Master data
INSERT INTO MST_ENERGY_TYPE VALUES (1,'電気','ELECT',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_ENERGY_TYPE VALUES (2,'ガス','GAS',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_ENERGY_TYPE VALUES (3,'太陽光','SUNLIGHT',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_ENERGY_TYPE VALUES (4,'EV充電','EV',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);

INSERT INTO MST_INVOICE_STATUS VALUES (1,'001','DRAFT','未確定',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_INVOICE_STATUS VALUES (2,'002','ISSUED','発行済',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_INVOICE_STATUS VALUES (3,'003','PAID','入金済',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_INVOICE_STATUS VALUES (4,'004','CANCELLED','取消',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);


-- MST_CUSTOMER_TYPE_CONVERSION
-- TARGET_TYPE=1（個人）
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (1,'001',1,'個人（通常）',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (2,'010',1,'個人（シニア）',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (3,'100',1,'個人（学生）',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
-- TARGET_TYPE=2（法人）
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (4,'002',2,'法人（中小）',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (5,'020',2,'法人（大手）',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (6,'200',2,'法人（外資）',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
-- TARGET_TYPE=3（その他）
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (7,'003',3,'その他（行政）',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (8,'030',3,'その他（団体）',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (9,'300',3,'その他（非営利）',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);

COMMIT;
EXIT;
